language: node_js
node_js:
  - "10"
dist: trusty

# We only deploy for staging and production as well as a PR.
if: (branch IN (master, production) AND type = push) OR (type = pull_request)

# We require sudo
sudo: required

# We only care for curl and jq (aws output parsing)
addons:
  apt:
    packages:
      - jq
      - curl
      
# Import AWS helper functions, as well as the AWS CLI
before_install:
    - source ./.travis/aws-helper.sh
    - sudo pip install awscli

# Jobs
jobs:
  include:
  - stage: Build Janis & Deploy
    script:
    # First we build it (yarn, yarn build)
    - janis_build
    # Once built we deploy to S3 bucket
    after_success:
    - janis_deploy