const footerSiteMapData = {
  en: [
    {
      url: '/themes/permits-tickets',
      text: 'Permits and tickets',
      id: 'VGhlbWVOb2RlOjE=',
      description: '',
      topics: [
        {
          url: '/topics/building-permits',
          text: 'Building permits',
          description: '',
          services: [],
        },
        {
          url: '/topics/business-permits-licenses',
          text: 'Business permits and licenses',
          description: '',
          services: [],
        },
        {
          url: '/topics/event-permits',
          text: 'Event permits',
          description: '',
          services: [],
        },
        {
          url: '/topics/pay-tickets',
          text: 'Pay tickets',
          description: '',
          services: [],
        },
      ],
    },
    {
      url: '/themes/housing-utilities',
      text: 'Housing and utilities',
      id: 'VGhlbWVOb2RlOjI=',
      description:
        'Find the resources to keep your home, apartment, or condo running smoothly.',
      topics: [
        {
          url: '/topics/pay-utility-bills',
          text: 'Pay utility bills',
          description: '',
          services: [],
        },
        {
          url: '/topics/water-electric-service',
          text: 'Water and electric service',
          description: '',
          services: [],
        },
        {
          url: '/topics/recycling-trash-compost',
          text: 'Recycling, trash, and compost',
          description:
            'The City of Austin provides hundreds of services to residents to help them manage things like recycling, trash, energy, and water. This is a short list of services that will grow over time.',
          services: [
            {
              url: '/services/bulk-item-pickup',
              text: 'Get ready for curbside bulk item pickup',
              id: 'U2VydmljZVBhZ2VOb2RlOjQ=',
            },
            {
              url: '/services/compost-pickup',
              text: 'Get ready for curbside compost pickup',
              id: 'U2VydmljZVBhZ2VOb2RlOjU=',
            },
            {
              url: '/services/hazardous-waste-dropoff',
              text: 'Drop off household hazardous waste and other recyclables',
              id: 'U2VydmljZVBhZ2VOb2RlOjY=',
            },
            {
              url: '/services/pickup-free-paint',
              text: 'Pick up free paint and other household items',
              id: 'U2VydmljZVBhZ2VOb2RlOjc=',
            },
          ],
        },
        {
          url: '/topics/housing-assistance',
          text: 'Housing assistance',
          description: '',
          services: [],
        },
      ],
    },
    {
      url: '/themes/pets',
      text: 'Pets',
      id: 'VGhlbWVOb2RlOjM=',
      description: '',
      topics: [
        {
          url: '/topics/pet-adoption',
          text: 'Pet adoption',
          description: '',
          services: [],
        },
        {
          url: '/topics/foster-animal',
          text: 'Foster an animal',
          description: '',
          services: [],
        },
        {
          url: '/topics/report-loose-animal',
          text: 'Report a loose animal',
          description: '',
          services: [],
        },
        {
          url: '/topics/lost-found-pets',
          text: 'Lost and found pets',
          description: '',
          services: [],
        },
      ],
    },
    {
      url: '/themes/health-safety',
      text: 'Health and safety',
      id: 'VGhlbWVOb2RlOjQ=',
      description: '',
      topics: [
        {
          url: '/topics/birth-certificates',
          text: 'Birth certificates',
          description: '',
          services: [],
        },
        {
          url: '/topics/healthcare-prevention',
          text: 'Healthcare and prevention',
          description: '',
          services: [],
        },
        {
          url: '/topics/find-childcare',
          text: 'Find childcare',
          description: '',
          services: [],
        },
        {
          url: '/topics/child-senior-safety',
          text: 'Child and senior safety',
          description: '',
          services: [],
        },
        {
          url: '/topics/disaster-safety-relief',
          text: 'Disaster safety and relief',
          description: '',
          services: [],
        },
        {
          url: '/topics/police-reports-records',
          text: 'Police reports and records',
          description: '',
          services: [],
        },
      ],
    },
    {
      url: '/themes/explore-visit',
      text: 'Explore and visit',
      id: 'VGhlbWVOb2RlOjU=',
      description: '',
      topics: [
        {
          url: '/topics/events-classes',
          text: 'Events and classes',
          description: '',
          services: [],
        },
        {
          url: '/topics/hike-bike-swim-play',
          text: 'Hike, bike, swim, and play',
          description: '',
          services: [],
        },
        {
          url: '/topics/arts-culture',
          text: 'Arts and culture',
          description: '',
          services: [],
        },
        {
          url: '/topics/libraries',
          text: 'Libraries',
          description: '',
          services: [],
        },
        {
          url: '/topics/transportation-parking',
          text: 'Transportation and parking',
          description: '',
          services: [],
        },
        {
          url: '/topics/airport',
          text: 'Airport',
          description: '',
          services: [],
        },
      ],
    },
    {
      url: '/themes/government-business',
      text: 'Government and business',
      id: 'VGhlbWVOb2RlOjY=',
      description: '',
      topics: [
        {
          url: '/topics/departments',
          text: 'Departments',
          description: '',
          services: [],
        },
        {
          url: '/topics/court-dates',
          text: 'Court dates and times',
          description: '',
          services: [],
        },
        {
          url: '/topics/business-development',
          text: 'Business development',
          description: '',
          services: [],
        },
        {
          url: '/topics/city-code',
          text: 'City code and ordinance',
          description: '',
          services: [],
        },
        {
          url: '/topics/budget-performance-open-records',
          text: 'Budget, performance, and open records',
          description: '',
          services: [],
        },
        {
          url: '/topics/funding-grants-rebates',
          text: 'Fudning, grants, and rebates',
          description: '',
          services: [],
        },
        {
          url: '/topics/resident-participation',
          text: 'Resident participation',
          description: '',
          services: [],
        },
        {
          url: '/topics/mayor-council',
          text: 'Mayor and Council',
          description: '',
          services: [],
        },
      ],
    },
    {
      url: '/themes/jobs',
      text: 'Jobs',
      id: 'VGhlbWVOb2RlOjc=',
      description: '',
      topics: [
        {
          url: '/topics/job-titles-pay',
          text: 'City job titles and pay',
          description: '',
          services: [],
        },
        {
          url: '/topics/benefits',
          text: 'City benefits',
          description: '',
          services: [],
        },
        {
          url: '/topics/rando-job-1',
          text: '[Job type 1]',
          description: '',
          services: [],
        },
        {
          url: '/topics/rando-job-2',
          text: '[Job type 2]',
          description: '',
          services: [],
        },
        {
          url: '/topics/all-jobs',
          text: 'All jobs',
          description: '',
          services: [],
        },
      ],
    },
  ],
  es: [
    {
      url: '/themes/permits-tickets',
      text: 'Permisos y multas',
      id: 'VGhlbWVOb2RlOjE=',
      description: '',
      topics: [
        {
          url: '/topics/building-permits',
          text: '',
          description: '',
          services: [],
        },
        {
          url: '/topics/business-permits-licenses',
          text: '',
          description: '',
          services: [],
        },
        {
          url: '/topics/event-permits',
          text: '',
          description: '',
          services: [],
        },
        { url: '/topics/pay-tickets', text: '', description: '', services: [] },
      ],
    },
    {
      url: '/themes/housing-utilities',
      text: 'Vivienda y servicios públicos',
      id: 'VGhlbWVOb2RlOjI=',
      description: '',
      topics: [
        {
          url: '/topics/pay-utility-bills',
          text: '',
          description: '',
          services: [],
        },
        {
          url: '/topics/water-electric-service',
          text: '',
          description: '',
          services: [],
        },
        {
          url: '/topics/recycling-trash-compost',
          text: 'Reciclaje, basura y compostaje',
          description: '',
          services: [
            {
              url: '/services/bulk-item-pickup',
              text:
                'Prepárese para la recolección de artículos grandes al borde de la acera',
              id: 'U2VydmljZVBhZ2VOb2RlOjQ=',
            },
            {
              url: '/services/compost-pickup',
              text: 'Prepárese para la recolección de compost',
              id: 'U2VydmljZVBhZ2VOb2RlOjU=',
            },
            {
              url: '/services/hazardous-waste-dropoff',
              text:
                'Entregue sus desechos peligrosos del hogar y otros artículos reciclables',
              id: 'U2VydmljZVBhZ2VOb2RlOjY=',
            },
            {
              url: '/services/pickup-free-paint',
              text: 'Recoja pintura y otros artículos del hogar gratis',
              id: 'U2VydmljZVBhZ2VOb2RlOjc=',
            },
          ],
        },
        {
          url: '/topics/housing-assistance',
          text: '',
          description: '',
          services: [],
        },
      ],
    },
    {
      url: '/themes/pets',
      text: 'Mascotas',
      id: 'VGhlbWVOb2RlOjM=',
      description: '',
      topics: [
        {
          url: '/topics/pet-adoption',
          text: '',
          description: '',
          services: [],
        },
        {
          url: '/topics/foster-animal',
          text: '',
          description: '',
          services: [],
        },
        {
          url: '/topics/report-loose-animal',
          text: '',
          description: '',
          services: [],
        },
        {
          url: '/topics/lost-found-pets',
          text: '',
          description: '',
          services: [],
        },
      ],
    },
    {
      url: '/themes/health-safety',
      text: 'Salud y seguridad',
      id: 'VGhlbWVOb2RlOjQ=',
      description: '',
      topics: [
        {
          url: '/topics/birth-certificates',
          text: '',
          description: '',
          services: [],
        },
        {
          url: '/topics/healthcare-prevention',
          text: '',
          description: '',
          services: [],
        },
        {
          url: '/topics/find-childcare',
          text: '',
          description: '',
          services: [],
        },
        {
          url: '/topics/child-senior-safety',
          text: '',
          description: '',
          services: [],
        },
        {
          url: '/topics/disaster-safety-relief',
          text: '',
          description: '',
          services: [],
        },
        {
          url: '/topics/police-reports-records',
          text: '',
          description: '',
          services: [],
        },
      ],
    },
    {
      url: '/themes/explore-visit',
      text: 'Explore y visite',
      id: 'VGhlbWVOb2RlOjU=',
      description: '',
      topics: [
        {
          url: '/topics/events-classes',
          text: '',
          description: '',
          services: [],
        },
        {
          url: '/topics/hike-bike-swim-play',
          text: '',
          description: '',
          services: [],
        },
        {
          url: '/topics/arts-culture',
          text: '',
          description: '',
          services: [],
        },
        { url: '/topics/libraries', text: '', description: '', services: [] },
        {
          url: '/topics/transportation-parking',
          text: '',
          description: '',
          services: [],
        },
        { url: '/topics/airport', text: '', description: '', services: [] },
      ],
    },
    {
      url: '/themes/government-business',
      text: 'Gobierno y negocios',
      id: 'VGhlbWVOb2RlOjY=',
      description: '',
      topics: [
        { url: '/topics/departments', text: '', description: '', services: [] },
        { url: '/topics/court-dates', text: '', description: '', services: [] },
        {
          url: '/topics/business-development',
          text: '',
          description: '',
          services: [],
        },
        { url: '/topics/city-code', text: '', description: '', services: [] },
        {
          url: '/topics/budget-performance-open-records',
          text: '',
          description: '',
          services: [],
        },
        {
          url: '/topics/funding-grants-rebates',
          text: '',
          description: '',
          services: [],
        },
        {
          url: '/topics/resident-participation',
          text: '',
          description: '',
          services: [],
        },
        {
          url: '/topics/mayor-council',
          text: '',
          description: '',
          services: [],
        },
      ],
    },
    {
      url: '/themes/jobs',
      text: 'Empleos',
      id: 'VGhlbWVOb2RlOjc=',
      description: '',
      topics: [
        {
          url: '/topics/job-titles-pay',
          text: '',
          description: '',
          services: [],
        },
        { url: '/topics/benefits', text: '', description: '', services: [] },
        { url: '/topics/rando-job-1', text: '', description: '', services: [] },
        { url: '/topics/rando-job-2', text: '', description: '', services: [] },
        { url: '/topics/all-jobs', text: '', description: '', services: [] },
      ],
    },
  ],
  vi: [
    {
      url: '/themes/permits-tickets',
      text: 'Giấy phép & Giấy phạt',
      id: 'VGhlbWVOb2RlOjE=',
      description: '',
      topics: [
        {
          url: '/topics/building-permits',
          text: '',
          description: '',
          services: [],
        },
        {
          url: '/topics/business-permits-licenses',
          text: '',
          description: '',
          services: [],
        },
        {
          url: '/topics/event-permits',
          text: '',
          description: '',
          services: [],
        },
        { url: '/topics/pay-tickets', text: '', description: '', services: [] },
      ],
    },
    {
      url: '/themes/housing-utilities',
      text: 'Nhà ở & Tiện ích',
      id: 'VGhlbWVOb2RlOjI=',
      description: '',
      topics: [
        {
          url: '/topics/pay-utility-bills',
          text: '',
          description: '',
          services: [],
        },
        {
          url: '/topics/water-electric-service',
          text: '',
          description: '',
          services: [],
        },
        {
          url: '/topics/recycling-trash-compost',
          text: 'Tái chế, rác, và phân ủ',
          description: '',
          services: [
            {
              url: '/services/bulk-item-pickup',
              text: 'Chuẩn bị cho việc bốc rác khối để lề đường',
              id: 'U2VydmljZVBhZ2VOb2RlOjQ=',
            },
            {
              url: '/services/compost-pickup',
              text: 'Chuẩn bị cho việc bốc rác phân ủ hữu cơ thường lệ',
              id: 'U2VydmljZVBhZ2VOb2RlOjU=',
            },
            {
              url: '/services/hazardous-waste-dropoff',
              text:
                'Bỏ đi các loại rác nhà nguy hiểm và các loại rác tái chế khác',
              id: 'U2VydmljZVBhZ2VOb2RlOjY=',
            },
            {
              url: '/services/pickup-free-paint',
              text: 'Lấy miễn phí sơn và các đồ dùng cho việc nhà khác',
              id: 'U2VydmljZVBhZ2VOb2RlOjc=',
            },
          ],
        },
        {
          url: '/topics/housing-assistance',
          text: '',
          description: '',
          services: [],
        },
      ],
    },
    {
      url: '/themes/pets',
      text: 'Thú vật nuôi',
      id: 'VGhlbWVOb2RlOjM=',
      description: '',
      topics: [
        {
          url: '/topics/pet-adoption',
          text: '',
          description: '',
          services: [],
        },
        {
          url: '/topics/foster-animal',
          text: '',
          description: '',
          services: [],
        },
        {
          url: '/topics/report-loose-animal',
          text: '',
          description: '',
          services: [],
        },
        {
          url: '/topics/lost-found-pets',
          text: '',
          description: '',
          services: [],
        },
      ],
    },
    {
      url: '/themes/health-safety',
      text: 'Sức khỏe $ An toàn',
      id: 'VGhlbWVOb2RlOjQ=',
      description: '',
      topics: [
        {
          url: '/topics/birth-certificates',
          text: '',
          description: '',
          services: [],
        },
        {
          url: '/topics/healthcare-prevention',
          text: '',
          description: '',
          services: [],
        },
        {
          url: '/topics/find-childcare',
          text: '',
          description: '',
          services: [],
        },
        {
          url: '/topics/child-senior-safety',
          text: '',
          description: '',
          services: [],
        },
        {
          url: '/topics/disaster-safety-relief',
          text: '',
          description: '',
          services: [],
        },
        {
          url: '/topics/police-reports-records',
          text: '',
          description: '',
          services: [],
        },
      ],
    },
    {
      url: '/themes/explore-visit',
      text: 'Khám phá $ Thăm viếng',
      id: 'VGhlbWVOb2RlOjU=',
      description: '',
      topics: [
        {
          url: '/topics/events-classes',
          text: '',
          description: '',
          services: [],
        },
        {
          url: '/topics/hike-bike-swim-play',
          text: '',
          description: '',
          services: [],
        },
        {
          url: '/topics/arts-culture',
          text: '',
          description: '',
          services: [],
        },
        { url: '/topics/libraries', text: '', description: '', services: [] },
        {
          url: '/topics/transportation-parking',
          text: '',
          description: '',
          services: [],
        },
        { url: '/topics/airport', text: '', description: '', services: [] },
      ],
    },
    {
      url: '/themes/government-business',
      text: 'Chính phủ $ Doanh nghiệp',
      id: 'VGhlbWVOb2RlOjY=',
      description: '',
      topics: [
        { url: '/topics/departments', text: '', description: '', services: [] },
        { url: '/topics/court-dates', text: '', description: '', services: [] },
        {
          url: '/topics/business-development',
          text: '',
          description: '',
          services: [],
        },
        { url: '/topics/city-code', text: '', description: '', services: [] },
        {
          url: '/topics/budget-performance-open-records',
          text: '',
          description: '',
          services: [],
        },
        {
          url: '/topics/funding-grants-rebates',
          text: '',
          description: '',
          services: [],
        },
        {
          url: '/topics/resident-participation',
          text: '',
          description: '',
          services: [],
        },
        {
          url: '/topics/mayor-council',
          text: '',
          description: '',
          services: [],
        },
      ],
    },
    {
      url: '/themes/jobs',
      text: 'Công việc',
      id: 'VGhlbWVOb2RlOjc=',
      description: '',
      topics: [
        {
          url: '/topics/job-titles-pay',
          text: '',
          description: '',
          services: [],
        },
        { url: '/topics/benefits', text: '', description: '', services: [] },
        { url: '/topics/rando-job-1', text: '', description: '', services: [] },
        { url: '/topics/rando-job-2', text: '', description: '', services: [] },
        { url: '/topics/all-jobs', text: '', description: '', services: [] },
      ],
    },
  ],
  ar: [
    {
      url: '/themes/permits-tickets',
      text: 'التصاريح والتذاكر',
      id: 'VGhlbWVOb2RlOjE=',
      description: '',
      topics: [
        {
          url: '/topics/building-permits',
          text: '',
          description: '',
          services: [],
        },
        {
          url: '/topics/business-permits-licenses',
          text: '',
          description: '',
          services: [],
        },
        {
          url: '/topics/event-permits',
          text: '',
          description: '',
          services: [],
        },
        { url: '/topics/pay-tickets', text: '', description: '', services: [] },
      ],
    },
    {
      url: '/themes/housing-utilities',
      text: 'الإسكان والمنافع',
      id: 'VGhlbWVOb2RlOjI=',
      description: '',
      topics: [
        {
          url: '/topics/pay-utility-bills',
          text: '',
          description: '',
          services: [],
        },
        {
          url: '/topics/water-electric-service',
          text: '',
          description: '',
          services: [],
        },
        {
          url: '/topics/recycling-trash-compost',
          text: 'إعادة التدوير والنفايات والسماد',
          description: '',
          services: [
            {
              url: '/services/bulk-item-pickup',
              text:
                'كُن على استعداد لجمع العناصر كبيرة الحجم التي يُراد التخلص منها على جانب الرصيف',
              id: 'U2VydmljZVBhZ2VOb2RlOjQ=',
            },
            {
              url: '/services/compost-pickup',
              text: 'كُن على استعداد لخدمة جمع السماد على جانب الرصيف',
              id: 'U2VydmljZVBhZ2VOb2RlOjU=',
            },
            {
              url: '/services/hazardous-waste-dropoff',
              text:
                'التخلص من النفايات الخطرة المنزلية وغيرها من المواد القابلة للتدوير',
              id: 'U2VydmljZVBhZ2VOb2RlOjY=',
            },
            {
              url: '/services/pickup-free-paint',
              text: 'اختيار الدهانات وغيرها من الأدوات المنزلية مجانا',
              id: 'U2VydmljZVBhZ2VOb2RlOjc=',
            },
          ],
        },
        {
          url: '/topics/housing-assistance',
          text: '',
          description: '',
          services: [],
        },
      ],
    },
    {
      url: '/themes/pets',
      text: 'لحيوانات الأليفة',
      id: 'VGhlbWVOb2RlOjM=',
      description: '',
      topics: [
        {
          url: '/topics/pet-adoption',
          text: '',
          description: '',
          services: [],
        },
        {
          url: '/topics/foster-animal',
          text: '',
          description: '',
          services: [],
        },
        {
          url: '/topics/report-loose-animal',
          text: '',
          description: '',
          services: [],
        },
        {
          url: '/topics/lost-found-pets',
          text: '',
          description: '',
          services: [],
        },
      ],
    },
    {
      url: '/themes/health-safety',
      text: 'الصحة والسلامة',
      id: 'VGhlbWVOb2RlOjQ=',
      description: '',
      topics: [
        {
          url: '/topics/birth-certificates',
          text: '',
          description: '',
          services: [],
        },
        {
          url: '/topics/healthcare-prevention',
          text: '',
          description: '',
          services: [],
        },
        {
          url: '/topics/find-childcare',
          text: '',
          description: '',
          services: [],
        },
        {
          url: '/topics/child-senior-safety',
          text: '',
          description: '',
          services: [],
        },
        {
          url: '/topics/disaster-safety-relief',
          text: '',
          description: '',
          services: [],
        },
        {
          url: '/topics/police-reports-records',
          text: '',
          description: '',
          services: [],
        },
      ],
    },
    {
      url: '/themes/explore-visit',
      text: 'الاستكشاف والزيارة',
      id: 'VGhlbWVOb2RlOjU=',
      description: '',
      topics: [
        {
          url: '/topics/events-classes',
          text: '',
          description: '',
          services: [],
        },
        {
          url: '/topics/hike-bike-swim-play',
          text: '',
          description: '',
          services: [],
        },
        {
          url: '/topics/arts-culture',
          text: '',
          description: '',
          services: [],
        },
        { url: '/topics/libraries', text: '', description: '', services: [] },
        {
          url: '/topics/transportation-parking',
          text: '',
          description: '',
          services: [],
        },
        { url: '/topics/airport', text: '', description: '', services: [] },
      ],
    },
    {
      url: '/themes/government-business',
      text: 'الحكومة والأعمال',
      id: 'VGhlbWVOb2RlOjY=',
      description: '',
      topics: [
        { url: '/topics/departments', text: '', description: '', services: [] },
        { url: '/topics/court-dates', text: '', description: '', services: [] },
        {
          url: '/topics/business-development',
          text: '',
          description: '',
          services: [],
        },
        { url: '/topics/city-code', text: '', description: '', services: [] },
        {
          url: '/topics/budget-performance-open-records',
          text: '',
          description: '',
          services: [],
        },
        {
          url: '/topics/funding-grants-rebates',
          text: '',
          description: '',
          services: [],
        },
        {
          url: '/topics/resident-participation',
          text: '',
          description: '',
          services: [],
        },
        {
          url: '/topics/mayor-council',
          text: '',
          description: '',
          services: [],
        },
      ],
    },
    {
      url: '/themes/jobs',
      text: 'الوظائف',
      id: 'VGhlbWVOb2RlOjc=',
      description: '',
      topics: [
        {
          url: '/topics/job-titles-pay',
          text: '',
          description: '',
          services: [],
        },
        { url: '/topics/benefits', text: '', description: '', services: [] },
        { url: '/topics/rando-job-1', text: '', description: '', services: [] },
        { url: '/topics/rando-job-2', text: '', description: '', services: [] },
        { url: '/topics/all-jobs', text: '', description: '', services: [] },
      ],
    },
  ],
};

export default footerSiteMapData;
